"use client";

import { jsPDF } from "jspdf";
import { Report, ReportAnalysis, ReportHistoryItem } from "./types";
import { useCallback } from "react";
import { Button } from "@/components/ui/button";

interface Props {
  report: Report | null;
  type?: string;
  analysis: ReportAnalysis | null;
  history?: ReportHistoryItem[] | null;
}

//IMAGE LOADER
const loadImage = (src: string): Promise<string> => {
  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.src = src;

    img.onload = () => {
      try {
        const canvas = document.createElement("canvas");
        canvas.width = img.width;
        canvas.height = img.height;

        const ctx = canvas.getContext("2d");
        if (!ctx) return resolve("");

        ctx.drawImage(img, 0, 0);
        resolve(canvas.toDataURL("image/png"));
      } catch {
        resolve("");
      }
    };

    img.onerror = () => resolve("");
  });
};

export const PrintButton = ({
  report,
  type,
  analysis,
}: Props) => {
  const handlePrint = useCallback(async () => {
    if (!report || !analysis) {
      alert("Report kosong");
      return;
    }
    const logo = await loadImage("/komo mascots.svg");

    const pdf = new jsPDF("p", "mm", "a4");

    const pageWidth = 210;
    const margin = 14;
    let y = 20;

    const line = (yPos: number) => {
      pdf.line(margin, yPos, pageWidth - margin, yPos);
    };

    const addTitle = () => {
    if (logo && logo.startsWith("data:image")) {
      try {
        pdf.addImage(logo, "PNG", margin, 8, 20, 20);
      } catch (e) {
      }
    }

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(18);

    pdf.text("KOMOLEARN REPORT", pageWidth / 2, 18, {
      align: "center",
    });

    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");

    line(34);
    y = 42;
  };

   const addTableHeader = () => {
    pdf.setFont("helvetica", "bold");

    pdf.text("No", 16, y);
    pdf.text("Question", 28, y);
    pdf.text("Answer", 95, y);
    pdf.text("Time", 145, y);
    pdf.text("Result", 170, y);

    y += 6;
    line(y);
    y += 6;
  };

    const addRow = (
    no: number,
    question: string,
    answer: string,
    time: number,
    result: string
  ) => {
    pdf.setFont("helvetica", "normal");

    const safeQuestion =
      question.length > 30
        ? question.slice(0, 30) + "..."
        : question;

    const safeAnswer =
      answer.length > 15
        ? answer.slice(0, 15) + "..."
        : answer;

    pdf.text(String(no), 16, y);
    pdf.text(safeQuestion, 28, y);
    pdf.text(safeAnswer, 95, y);
    pdf.text(`${time}s`, 145, y);
    pdf.text(result, 170, y);

    y += 7;
  };

    //START
    addTitle();

        pdf.setFontSize(11);
        pdf.setFont("helvetica", "bold");

        pdf.text("Student Information", margin, y);

        y += 8;

        pdf.setFont("helvetica", "normal");

        pdf.text(`Student : ${report.name ?? "Unknown"}`, margin, 50);
        pdf.text(`Type : ${type ?? "-"}`, margin, 56);
        pdf.text(`Score : ${report.score}`, margin, 62);
        pdf.text(`Accuracy : ${analysis.accuracy.toFixed(1)}%`, margin, 68);
        pdf.text(`Time Spent : ${report.timeSpent}s`, margin, 74);
        pdf.text(`Generated : ${new Date().toLocaleDateString()}`, margin, 80);

        y = 90;
        line(84);
        y = 92;

    addTableHeader();

    (report.questions ?? []).forEach((q, i) => {

      addRow(
      i + 1,
      q.question ?? "-",
      q.userAnswer ?? "-",
      q.timeSpent ?? 0,
      q.isCorrect ? "Correct" : "Wrong"
    );
    });

    const checkPage = () => {
    if (y > 270) {
      pdf.addPage();

      y = 20;

      addTitle();

      y = 50;

      addTableHeader();
    }
  };

    const pageCount = pdf.getNumberOfPages();

    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);

      pdf.setFontSize(8);

      pdf.text(
        "Generated by KomoLearn",
        pageWidth / 2,
        290,
        { align: "center" }
      );
    }

    pdf.save("komolearn-report.pdf");
  }, [report, analysis, type]);

  return (
    <Button
    variant="secondary"
      type="button"
      onClick={handlePrint}
      className="w-full"
    >
      Export PDF
    </Button>
  );
};